// Speaker notes for presenter.html — edit freely. Keys are frame labels.
window.DECK = {
  "labels": [
    "T-01",
    "T-02",
    "T-03",
    "D-03",
    "D-03b",
    "D-04",
    "D-05",
    "D-06",
    "DF-00",
    "DF-01",
    "DF-02",
    "DF-03",
    "DF-04a",
    "DF-04b",
    "DF-04c",
    "P-00a-photo",
    "P-00a",
    "P-00b-blank",
    "P-00b",
    "P-00d",
    "P2-01",
    "P2-02",
    "P2-03",
    "P-14b",
    "MO-01",
    "M-00",
    "M-01",
    "M-02",
    "M-03",
    "M-04",
    "M-05",
    "M-06",
    "M-07",
    "M-08",
    "M-09",
    "M-10",
    "M-09b",
    "PR-01",
    "PR-02",
    "PR-04",
    "PR-05",
    "PC-01",
    "PC-02",
    "PC-04a",
    "PC-04b",
    "PC-04c",
    "PC-04d",
    "PC-06",
    "PC-07",
    "PC-08",
    "PC-10b",
    "PC-11",
    "TL-01",
    "TL-02"
  ],
  "notes": {
    "T-01": "The last time I had my eyes checked was in 2014. That year, everything changed for me. I got lasik eye surgery.\n\nMy parents both had it done the old-fashioned way with scalpels, like 20 years before.\n\n▸ Hold. No build.",
    "T-02": "I got the double whammy in 7th grade: glasses and braces, all at once.\n\n▸ Team photo, 2004. Let them find you.",
    "T-03": "I hated glasses. I didn't like that my peripheral was blurry if I glanced down without moving my head. I hated dozing off unintentionally and waking up to my frames being bent.\n\nI got contacts almost immediately. Hated those things too.\n\nWhen my parents wanted to gift me lasik, I had no hesitations. Top 10 best decisions of my life. For the first time in years I saw clearly… all the time. I didn't need to wake up to a series of steps just to see. I could just see.\n\nIt's amazing what having the right lens can do. Today, that's what we're going to do. [put on the blue-light glasses] We're going to put on some Biblical lenses that help us better exegete God's Word.\n\n▸ Zoom pushes in; the ring draws around you.",
    "D-03": "DEMO · 5 min\n\nRead 2:5–11 cold.\n\n▸ Only 2:5–11 at full weight. Columns one and three held empty.",
    "D-03b": "Ask: what would you preach?\n\nEveryone will say \"be humble like Jesus.\" ",
    "D-04": "Let's look before this text, at 2:1–4.\n\n▸ 2:1–4 appears left; 5–11 dims.",
    "D-05": "Now the \"therefore\" in 2:12.\n\nPaul's argument in Philippians is about unity in a divided church.\n\nLook at 4:2—Euodia and Syntyche—humility is the means, not the point.\n• Contention in the church focused on two female leaders, Euodia and Syntyche.\n• Having dealt with deep divisions in Corinth (1 Cor 1:10–12), Paul does not want this to develop any further.\n• Paul tells them how to live—negatively first, then positively (2:3–4).\n\n▸ 2:12 lands in the third column; \"therefore\" marked.",
    "D-06": "A message that starts at v.5 preaches a real idea that isn't this text's idea.\n\nThat is the cost of skipping exegesis.",
    "DF-00": "DEFINE · 5 min\n\nDefine the term before the lenses.",
    "DF-01": "Exegesis IS NOT discovering what we think it means.\n\nIf you read 2:5–11 in a vacuum you'll likely walk away assuming it is about 1) humility and 2) Christ's deity. But why is Paul calling for humility?",
    "DF-02": "Exegesis IS NOT making the text mean what we want it to mean.\n\nIf you go to 2:5–11 to prove the point of humility alone, it's not the most honoring thing you can do.",
    "DF-03": "Exegesis IS discovering what the Biblical author intended.\n\nDo your due diligence to the text and you'll realize the tone is joyful—Paul to his brothers and sisters—but firm in calling out a real problem in the Philippian church: disunity.\n\nPaul did not write this as a deep theology lesson. He used Jesus's ultimate example of humility to solve a practical problem: he wanted the church to stop arguing, put away their pride, and live in unity.\n\n▸ Both negatives strike through; the positive lands.",
    "DF-04a": "Exegesis is an effort at reaching back into history to the original author and audience.",
    "DF-04b": "Hermeneutics is about discovering why the text is relevant for here and now.\n\nHermeneutics focuses on the principles of interpretation—how the process works, the \"rules\" for searching out meaning. Exegesis applies those principles.",
    "DF-04c": "Good hermeneutics stems from good exegesis.",
    "P-00a-photo": "PHOROPTER · 10 min\n\nSo how do we achieve textual clarity? Let's do a quick visit to the eye doctor.\n\nAnyone know what this machine is called? Surely you've sat in front of one of these in your life.\n\n▸ Photo only. Let them look before you name it.",
    "P-00a": "It's called a phoropter.",
    "P-00b-blank": "You sit down in front of one of these and hear a familiar saying…\n\n\"Better one…\" ",
    "P-00b": " \"…or two?\" ",
    "P-00d": "▸ Blank lens drops in. Three lens drops coming—others, you, author.",
    "P2-01": "LENS DROP #1 → Applied Meaning (others)\n\nStart with others = you allow circumstances to direct the textual meaning.\n\nExample: ________\n\nStill a necessary lens, but more is needed.\n\n▸ Scripture stays blurred.",
    "P2-02": "LENS DROP #2 → Personal Exposure (you)\n\nStart with you = self-fulfilling fallacy; your assumptions change the meaning.\n\nExample: ________\n\nStill a necessary lens, but more is needed.\n\n▸ Still blurred.",
    "P2-03": "LENS DROP #3 → Original Intent (author)\n\nStart with origin = brings clarity to your life and, by association, others' lives.\n\n▸ Scripture snaps crisp.",
    "P-14b": "Once you have the right lenses to look through, you get textual clarity. That's what biblical exegesis is all about.\n\nA right view of the author's intent allows the Spirit to expose for you the work God wants to do in you—which in turn flows through you to others.\n\n[The illustration sort of breaks down—you don't start with others or you, but you do need those lenses to get the full picture.]\n\nNow let's pick up a pair of glasses and see what we see.",
    "MO-01": "EXEGESIS METHOD OVERVIEW · 10 min\n\nWalk through the method, then release them to do it. Provide the QR for digital note-takers.",
    "M-00": "Nine steps. About five hours.\n\n▸ Empty spine—the shape of the process before anything fills it.",
    "M-01": "01 SPIRITUAL PREPAREDNESS · 15 min\n\nSearch your own heart for what you are bringing into your study—biases, sin, struggles. Pray.",
    "M-02": "02 READ THE WHOLE LETTER · 15 min\n\nIn one sitting, read the whole letter for context before you begin studying.",
    "M-03": "03 OBSERVATIONS + QUESTIONS · 30 min\n\nNotate your questions and observations verse by verse.",
    "M-04": "04 LITERARY CONTEXT · 20 min\n\nBriefly explain what precedes and follows your text.\n1. What comes before your text?\n2. What comes after your text?\n3. How does your text fit the author's flow of thinking?",
    "M-05": "05 HISTORICAL CONTEXT · 20 min\n\nIdentify important cultural context surrounding the author's time and location of writing.",
    "M-06": "06 EXEGETICAL DOMINANT THOUGHT · 20 min\n\nState the point of the text in one sentence.",
    "M-07": "07 COMMENTARY RESEARCH · 120 min\n\nGather further perspective around your passage from trusted sources.",
    "M-08": "08 DRAFT SERMON OUTLINE · 60 min\n\nThis is a starting line based on your study up to this point.\nMain idea (dominant thought) · introduction · main points (2–3) · conclusion · illustrations · application.",
    "M-09": "09 REFINE · ongoing\n\nThe earlier you can prepare, the more time you have to refine.",
    "M-10": "All nine together with the time budget.\n\n▸ Hold frame—this one gets photographed. Point them to the worksheets / QR.",
    "M-09b": "▸ The nine steps as an eye chart. Lightbox flickers on; rows sharpen top to bottom. Let it land, then move.",
    "PR-01": "PHILIPPIANS 2 · 15 min\n\nSkipping the first two steps, we're going to take a few minutes to read Philippians 2 and have you write down your initial observations and questions.\n\n[Weigh the option of a real-time inductive study vs. letting them do their own observations.]\n\n▸ Instruction stays up while they work.",
    "PR-02": "▸ Countdown inside the lens. Press t to start / pause, ⇧T to reset. Click the time to change it.",
    "PR-04": "Now that you have your initial thoughts captured, you have what you bring into the text—what you know, what you don't know, what you need to learn more about.\n\nWhen you dig back in and start studying, you can compare what you got out of it before allowing other voices to craft your thinking.",
    "PR-05": "▸ Optional holding frame for discussion.",
    "PC-01": "PRACTICAL · 10 min\n\nInput · Output · Constraints",
    "PC-02": "INPUT (growth)\n\nHow's your personal quiet time?\nHow do you collect ideas?\nWhat sources are you listening to?\n\nIf I'm not reading, I'm not growing.",
    "PC-04a": "OUTPUT (discipleship)\n\nAnyone able to identify this location?\n\n▸ Just the picture. Let them look.",
    "PC-04b": "Sea of Galilee and the Dead Sea.\n\nThese two bodies of water are a real-life example of input and output.",
    "PC-04c": "They share the same input: the Jordan River flows in from the north and through the Sea of Galilee, then continues down to the Dead Sea. That's where the problem occurs.\n\nThe Dead Sea gets its name from the lack of life in its waters. Fish can't live there. Nothing grows around the lake. All that input from the north has no output, and the very water that gives the lake its form poisons it.",
    "PC-04d": "For Christians, it's a good reminder: all the input in the world will only poison the mission of God if it has no output. Output looks like preaching, teaching, training—but more importantly, it's discipling others.\n\nPractically, for me this looked like:\n• My time in college leading my first Bible study.\n• Dale Bruner commentary + little black journals.\n• I had to read the Bible for myself in order to give it away. Transformation in me led to transformation in others.\n• Like Jesus material rekindled my walk.",
    "PC-06": "CONSTRAINTS\n\nWhat do you do when the needs of the people leave no time to prepare for a message?",
    "PC-07": "What do you do when your personal needs are greater than the ministry needs?",
    "PC-08": "What do you do when you have no control over the desired outcome, but you disagree with the direction? (Expository vs. topical.)\n\nHow do you honor someone else's creative request and still honor the biblical text?",
    "PC-10b": "Learning to exegete the people will help you exegete the text.\n\nA lost person needs… a new believer needs… a stuck follower needs… a prideful worker needs… a hopeless disciple-maker needs…\n\nUse the 4 Chair framework to explain how to be adaptable.",
    "PC-11": "COMMON MISTAKES\n\n1. We jump to reading other people's work on a text without first allowing God to use the text to work in us.\n2. We become burdened by the demand of studying by losing perspective on the fruit God bears in us through studying.\n3. We waste time chasing the right study formula, the right tools, at the expense of just enjoying being in God's Word.\n\n▸ Three beats build in.",
    "TL-01": "TOOLS · 5 min\n\nLife Application Study Bible · Commentaries (The Gospel Coalition) · the 9 worksheets (Cino) · Blue Letter Bible · Logos.\n\n▸ Wear the tool belt. Slides stay plain.",
    "TL-02": "You will always have more tools at your disposal than necessary. Your job is to know which tool on your belt is needed, and for when."
  }
};
