// Speaker notes for presenter.html — edit freely. Keys are frame labels.
window.DECK = {
  "labels": [
    "T-01",
    "D-00a",
    "D-00a2",
    "D-00a3",
    "D-00b",
    "D-03",
    "D-03b",
    "D-04",
    "D-05",
    "D-06",
    "DF-00",
    "DF-01",
    "DF-02",
    "DF-03",
    "DF-04",
    "P-00a",
    "P-00b-blank",
    "P-00b",
    "P-00d",
    "P2-01",
    "P2-02",
    "P2-03",
    "P-14",
    "MO-01",
    "M-00",
    "M-01",
    "M-02",
    "M-03",
    "M-04",
    "M-05",
    "M-06",
    "M-07",
    "M-08",
    "M-09",
    "M-10",
    "M-09b",
    "PR-01",
    "PR-02",
    "PR-04",
    "PR-05",
    "PC-01",
    "PC-02",
    "PC-04a",
    "PC-04b",
    "PC-04c",
    "PC-04d",
    "PC-05",
    "PC-06",
    "PC-07",
    "PC-08",
    "PC-10",
    "PC-11",
    "TL-01",
    "TL-02"
  ],
  "notes": {
    "T-01": "Hold. No build. Lens photo (original letters) pushed right; title bottom-left on a tapered plate.",
    "D-00a": "Still. Open bible, 2:5–11 marked.",
    "D-00a2": "One page turns back: 2:1–4 comes into view. What comes before?",
    "D-00a3": "Two turns forward: past 5–11, landing on 2:12 — the therefore.",
    "D-00b": "Bible partially in frame; passage sits on the dark ground, not on the book.",
    "D-03": "Same grid, only 2:5–11 shown at full weight. Columns one and three held empty.",
    "D-03b": "Question lands beside the passage, arrow pointing at it. Nothing else moves.",
    "D-04": "Pull back: 2:1–4 appears left of the passage; 5–11 dims. Third column held empty.",
    "D-05": "2:12 lands in the held third column; nothing else moves. 'therefore' marked in the lens tone.",
    "D-06": "Landing line. Margin card is optional.",
    "DF-00": "Section marker. Define the term before the lenses.",
    "DF-01": "First negative definition. Lines two and three held invisible so nothing moves.",
    "DF-02": "Line one quiets; line two lands in place.",
    "DF-03": "Both negatives strike through; the positive lands full weight.",
    "DF-04": "Two objects, one relationship.",
    "P-00a": "What a phoropter is. Archival photo, full bleed. Hold.",
    "P-00b-blank": "Blank chart — no letters.",
    "P-00b": "A few steps back, looking through the lens. Real photo. Sets up the step-behind.",
    "P-00d": "Duplicate of P-00c with the chart removed — blank lens.",
    "P2-01": "Lens 1: Applied Meaning (others). Scripture stays blurred behind an amber lens.",
    "P2-02": "Lens 2: Personal Exposure (you). Still blurred.",
    "P2-03": "Lens 3: Original Intent (author). Scripture snaps crisp.",
    "P-14": "Mask fully retracts; ground returns to light. Sets up the method.",
    "MO-01": "Section marker. Now the method.",
    "M-00": "Empty spine — the shape of the process before anything fills it.",
    "M-01": "Step 1 lands.",
    "M-02": "Step 2 lands.",
    "M-03": "Step 3 lands.",
    "M-04": "Step 4 lands.",
    "M-05": "Step 5 lands.",
    "M-06": "Step 6 lands.",
    "M-07": "Step 7 lands.",
    "M-08": "Step 8 lands.",
    "M-09": "Step 9 lands.",
    "M-10": "Hold frame. All nine together with the time budget — this one gets photographed.",
    "M-09b": "The nine steps as an eye chart. Lightbox flickers on; rows sharpen top to bottom.",
    "PR-01": "Instruction. Stays up while they work.",
    "PR-02": "Live countdown inside the lens. Click the time to start/pause; double-click resets to 15:00.",
    "PR-04": "Quote setting.",
    "PR-05": "Optional holding frame for discussion.",
    "PC-01": "Section marker.",
    "PC-02": "Input: growth.",
    "PC-04a": "Just the picture. Let them look.",
    "PC-04b": "Name the two seas.",
    "PC-04c": "Tags land: in and out lives; in with no out dies.",
    "PC-04d": "Same river feeds both. Galilee has an outlet and lives; the Dead Sea has none. Input alone doesn't make you alive.",
    "PC-05": "Quote setting.",
    "PC-06": "Constraints, question one.",
    "PC-07": "Constraints, question two.",
    "PC-08": "Constraints, question three. Exegetical vs. topical preaching.",
    "PC-10": "Four needs, 4 Chair framework.",
    "PC-11": "Common mistakes; three beats build in. Amber lives only here and on the wrong lenses.",
    "TL-01": "The tool belt is the prop. Slides stay plain.",
    "TL-02": "Quote setting."
  }
};
